/**
 * SPDX-FileCopyrightText: (c) 2024 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package esami.model.impl;

import esami.model.Exam;

import esami.service.ExamLocalServiceUtil;

/**
 * The extended model base implementation for the Exam service. Represents a row in the &quot;FOO_Exam&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExamImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExamImpl
 * @see Exam
 * @generated
 */
public abstract class ExamBaseImpl extends ExamModelImpl implements Exam {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a exam model instance should use the <code>Exam</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ExamLocalServiceUtil.addExam(this);
		}
		else {
			ExamLocalServiceUtil.updateExam(this);
		}
	}

}